image_type: rgb
task_type: 1

task_0:
  image_path: ""
  save_path: ""
  rate: 0.3

task_1:
  image_path: ""
  save_path: ""
  size: 255
  stride: 12
  pad_zero: null

task_2:
  image_path: ""
  save_path: ""

task_3:
  image_path: ""
  save_path: ""
  label_mapping:
    {
      "water": [0, 0, 255],
      "baresoil": [139, 0, 0],
      "road": [83, 134, 139],
      "industry": [255, 0, 0],
      "vegetation": [0, 255, 0],
      "residential": [205, 173, 0],
      "plantingarea": [139, 105, 20],
      "other": [178, 34, 34],
      "farms": [0, 139, 139],
    }

task_4:
  image_path: ""
  save_path: ""
  label_mapping:
    {
      "water": [0, 0, 255],
      "baresoil": [139, 0, 0],
      "road": [83, 134, 139],
      "industry": [255, 0, 0],
      "vegetation": [0, 255, 0],
      "residential": [205, 173, 0],
      "plantingarea": [139, 105, 20],
      "other": [178, 34, 34],
      "farms": [0, 139, 139],
    }

task_5:
  true_label_path: ""
  pre_label_path: ""

task_6:
  image_path: ""
  label_path: ""
  save_path: ""
  rate: ""
